'use strict';
const tg=window.Telegram?.WebApp;tg?.ready();tg?.expand();
const $=id=>document.getElementById(id),fmt=x=>Number.isFinite(x)?x.toLocaleString('tr-TR',{maximumFractionDigits:2}):'—';
const escape=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let data=null,tab='all',limit=40,query='',watch=new Set();
try{watch=new Set(JSON.parse(localStorage.getItem('mk-watch')||'[]'));}catch{}
async function api(path){const r=await fetch(path,{headers:{'X-Telegram-Init-Data':tg?.initData||''},cache:'no-store'});if(!r.ok)throw Error(r.status===401?'Uygulamayı botun içinden aç. Oturum süresi dolduysa kapatıp yeniden aç.':'Veriler alınamadı; bağlantıyı kontrol et.');return r.json();}
function money(x){return Number.isFinite(x)?fmt(x)+' TL':'—';}
function rows(){let rs=data.rows;if(tab==='top')rs=data.top15.map(t=>rs.find(r=>r.ticker===t)).filter(Boolean);else if(tab==='five')rs=data.portfolio5.map(t=>rs.find(r=>r.ticker===t)).filter(Boolean);else if(tab==='watch')rs=rs.filter(r=>watch.has(r.ticker));return rs.filter(r=>(r.ticker+' '+(r.company||'')).toLocaleUpperCase('tr-TR').includes(query));}
function render(){if(!data)return;const rs=rows(),rank=new Map(data.top15.map((t,i)=>[t,i+1]));$('cards').innerHTML=rs.slice(0,limit).map(r=>`<button class="card" data-ticker="${escape(r.ticker)}"><div class="card-head"><div><span class="rank">${rank.has(r.ticker)?'#'+rank.get(r.ticker):''}</span><span class="symbol">${escape(r.ticker)}</span></div><span>${watch.has(r.ticker)?'⭐':'›'}</span></div><div class="grid"><div class="cell"><small>Fiyat</small><strong>${money(r.price)}</strong></div><div class="cell"><small>Baz değer</small><strong>${money(r.fair_value)}</strong></div><div class="cell"><small>Potansiyel</small><strong class="${r.potential>=0?'potential':'negative'}">${Number.isFinite(r.potential)?'%'+fmt(r.potential):'—'}</strong></div></div><span class="tag ${r.status==='HESAPLANDI'?'good':''}">${escape(r.status.replaceAll('_',' '))}</span><p class="previous">Bilanço: ${escape(r.period||'Henüz hesap yok')}${r.target_context?.previous_filing_target?' · Önceki baz: '+money(r.target_context.previous_filing_target.fair_value):''}</p></button>`).join('')||'<p class="muted">Bu görünümde hisse bulunamadı.</p>';$('more').hidden=rs.length<=limit;}
async function load(){try{data=await api('/api/snapshot');const priced=data.rows.filter(r=>r.status==='HESAPLANDI'),positive=priced.filter(r=>Number.isFinite(r.potential));const avg=positive.length?positive.reduce((s,r)=>s+r.potential,0)/positive.length:null;$('stats').innerHTML=`<div><strong>${data.total}</strong><small>Evren kodu</small></div><div><strong>${priced.length}</strong><small>Fiyatlı hesap</small></div><div><strong>${Number.isFinite(avg)?'%'+fmt(avg):'—'}</strong><small>Ort. potansiyel</small></div>`;$('stamp').textContent='Son tarama: '+(data.as_of||'Henüz yapılmadı');$('notice').textContent=(data.stale?'Tarama eski veya henüz yok. Botta /kapguncelle çalıştır. ':'')+'500 fiyatlı değerleme ve yatırım doğrulaması henüz tamamlanmadı. Yeni bilanço hedefleri otomatik kontrollerde güncellenir.';render();}catch(e){$('notice').textContent=e.message;}}
async function detail(ticker){const r=data.rows.find(r=>r.ticker===ticker);if(!r)return;const c=r.target_context||{},prev=c.previous_filing_target,last=c.last_valid_target;
$('detailBody').innerHTML=`<h2>${escape(r.ticker)}</h2><p class="muted">${escape(r.company)}</p><button id="watchToggle">${watch.has(ticker)?'⭐ Takipten çıkar':'☆ Takibe ekle'}</button><p>${escape(r.status)} · ${escape(r.period||'—')}<br>Rapor yayını: ${escape(r.published_at||'—')}</p><div class="grid">${Object.entries(r.bands||{}).map(([k,b])=>`<div class="cell"><small>${escape({bear:'Senaryo 1',base:'Baz',bull:'Senaryo 3'}[k])}</small><strong>${money(b.price)}</strong></div>`).join('')}</div>${prev?'<p>Önceki bilanço hedefi: <b>'+money(prev.fair_value)+'</b> · '+escape(prev.period_end)+'</p>':''}${Number.isFinite(c.target_change_pct)?'<p>Hedef değişimi: %'+fmt(c.target_change_pct)+'</p>':''}${!c.current_target_available&&last?'<p class="negative">Yeni hedef doğrulanamadı. Son geçerli eski hedef: '+money(last.fair_value)+' · '+escape(last.period_end)+'. Güncel hedef veya satış talimatı değildir.</p>':''}<p>${escape(r.reason||'')}</p><ul>${(r.warnings||[]).map(w=>'<li>'+escape(w)+'</li>').join('')}</ul><div id="sources"></div><h3>Bilanço hedef geçmişi</h3><div id="history">Yükleniyor…</div>`;
const urls=(r.source_urls||[]).filter(u=>/^https:\/\/(www\.)?kap\.org\.tr\/tr\/Bildirim\/\d+$/.test(u));$('sources').innerHTML=urls.map(u=>`<p><a href="${escape(u)}" target="_blank" rel="noopener noreferrer">KAP raporunu aç ↗</a></p>`).join('');$('watchToggle').onclick=()=>{watch.has(ticker)?watch.delete(ticker):watch.add(ticker);try{localStorage.setItem('mk-watch',JSON.stringify([...watch]));}catch{}render();detail(ticker);};if(!$('detail').open)$('detail').showModal();
try{const hs=await api('/api/history/'+encodeURIComponent(ticker));if($('detailBody').querySelector('h2')?.textContent!==ticker)return;$('history').innerHTML=hs.map(h=>`<div class="history"><strong>${escape(h.period_end)} · ${money(h.fair_value)}</strong><p class="muted">${escape(h.published_at)} · ${escape(h.model_version)}</p></div>`).join('')||'Bu kurulumda geçmiş hedef kaydı yok.';}catch(e){$('history').textContent=e.message;}}
$('search').oninput=e=>{query=e.target.value.toLocaleUpperCase('tr-TR');limit=40;render();};document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;limit=40;document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('selected',x===b));render();});$('cards').onclick=e=>{const card=e.target.closest('[data-ticker]');if(card)detail(card.dataset.ticker);};$('more').onclick=()=>{limit+=40;render();};$('close').onclick=()=>$('detail').close();load();setInterval(load,60000);
